config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  get "/dashboard", to: "dashboard#show", as: "dashboard"

  resources :leagues
  resources :seasons, except: [:index] do
    member do
      get "standings", to: "standings#show"
    end
  end

  resources :picks, only: [:index, :create, :destroy]

  namespace :admin do
    get "/winners", to: "winners#index"
    post "/winners", to: "winners#create"
  end

  get "/unsubscribe", to: "unsubscribe#reminders"
end

app/models/season.rb
class Season < ApplicationRecord
  include DateHelper
  belongs_to :league
  has_many :game_weeks, dependent: :destroy

  validates_presence_of :name
  validates_uniqueness_of :name, scope: :league_id
  validates_presence_of :start_date
  validates_presence_of :end_date 
  after_create_commit :create_game_weeks

  def all_dates
    (start_date..end_date).to_a
  end

  def days_left
    (end_date - today).to_i + 1 if end_date > today
  end
  
  def full_stats_standings(limit = nil)
    users = standings(limit)
    users.map do |user|
      all_picks = user.picks.where(game_week: game_weeks)
      total_pick_count = all_picks.where.not(status: nil).count
      nil_pick_count = all_picks.where(status: nil).where('date < ?', today).count
      user.total_pick_count = total_pick_count
      user.nil_pick_count = nil_pick_count
      user
    end
  end

  def league_name
    league.name
  end

  def other_users(user_id)
    users = UserDecorator.decorate_collection(league.memberships.where.not(user_id: user_id).map(&:user))
    users.sort_by { |u| u.email }
  end

  def points_for_user(user)
    standings.find { |u| u.id == user.id }.pick_count
  end

  def position_for_current_user(user)
    ordered_standings = standings
    index = ordered_standings.index(user) || 98
    {place: index + 1, object: ordered_standings[index]&.decorate}
  end

  def standings(limit = nil)
    User
      .joins(:picks)
      .where(picks: {status: :winner, game_week: game_weeks})
      .select("users.*, count(picks.id) as pick_count")
      .group("users.id")
      .order("count(picks.id) DESC")
      .limit(limit).decorate
  end

  def player_count
    standings.to_a.count
  end

  private

  def create_game_weeks
    create_short_week if offset > 0
    adjusted_start_date = start_date + offset
    n = 0
    loop do
      gw_start_date = adjusted_start_date + increment_lock * n
      calculated_end = gw_start_date + (increment_lock - 1)
      gw_end_date = verified_end_date(calculated_end, end_date)
      game_weeks.create!(start_date: gw_start_date, end_date: gw_end_date)
      break if calculated_end >= end_date
      n += 1
    end
  end

  def create_short_week
    game_weeks.create(start_date: start_date, end_date: start_date + (offset - 1))
  end

  def verified_end_date(calculated_end_date, season_end_date)
    calculated_end_date > season_end_date ? season_end_date : calculated_end_date
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :authenticate_user!

  def show
    @season = Season.find(params[:id]).decorate
    authorize @season
    today = DateTime.now.in_time_zone("America/Denver").to_date
    end_of_week = today + @season.increment_lock
    end_date = end_of_week > @season.end_date ? @season.end_date : end_of_week
    @current_week = (today..end_date).to_a
    @all_picks = Pick.where(game_week_id: @season.game_weeks.map(&:id))
  end

  def new
    @league = League.find(params[:league_id])
    @season = @league.seasons.new
    authorize @season
  end

  def create
    league = League.find(season_params[:league_id])
    @season = league.seasons.new(season_params)
    authorize @season
    if @season.save
      redirect_to @season
    else
      render :new
    end
  end

  def edit
    @season = Season.find(params[:id])
    authorize @season
  end

  def update
    @season = Season.find(params[:id])
    authorize @season
    if @season.update(season_params)
      redirect_to @season
    else
      render :edit
    end
  end

  def destroy
    @season = Season.find(params[:id])
    authorize @season
    @league = @season.league
    @season.destroy!
    redirect_to @league
  end

  private

  def season_params
    params.require(:season).permit(:name, :active, :league_id, :start_date, :end_date, :increment_lock, :offset)
  end
end

app/views/seasons/edit.html.erb
<%= form_for @season do |f| %>
  <%= f.label :name, "Season Name" %>
  <%= f.text_field :name %>
  <%= f.submit "Update Season" %>
<% end %>

app/views/seasons/new.html.erb
<div class="container">
  <div class="row one-half-column">
    <div class="one-half column">
      <%= form_for @season do |f| %>
        <%= f.hidden_field :league_id, value: params[:league_id] %>
        <div class="field">
            <%= f.label :name, "Season Name" %>
            <%= f.text_field :name, class: "u-full-width" %>
        </div>
        <div class="field">
          <%= f.label :start_date, "Start Date" %>
          <%= f.date_field :start_date, class: "u-full-width" %>
        </div>
        <div class="field">
          <%= f.label :end_date, "End Date" %>
          <%= f.date_field :end_date, class: "u-full-width" %>
        </div>
        <div class="field">
          <%= f.label :increment_lock, "Days in Betting Window" %>
          <%= f.text_field :increment_lock, class: "u-full-width" %>
        </div>
        <div class="field">
          <%= f.label :offset %>
          <%= f.text_field :offset, class: "u-full-width" %>
        </div>
        <div class="actions">
          <%= f.submit "Create Season", class: "u-full-width" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/seasons/show.html.erb
<div class="container">
  <div class="button-actions-row">
    <%= link_to "Back to League", @season.league, class: "btn btn-outline-primary btn-sm" %>
    <% if policy(@season).destroy? %>
      <%= button_to "Delete Season", @season, method: :delete, class: "btn btn-outline-danger btn-sm" %>
      <%= button_to "Finalize Season", @season, method: :put, class: "btn btn-outline-info btn-sm", params: { season: { active: false } } %>
    <% end %>
  </div>
  <h4><%= @season.name %></h4>
  <div class="row">
    <div class="col-md-6">
      <h5>Season Overview</h5>
      <ul>
        <li>Start Date: <%= @season.formatted_start_date %></li>
        <li>End Date: <%= @season.formatted_end_date %></li>
        <li>Days: <%= season_days(@season) %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <h5>Top 3</h5>
      <div class="table-responsive">
        <table class="table table-sm">
          <tr>
            <th>Place</th>
            <th>Person</th>
            <th>Points</th>
          </tr>
          <% @season.standings(3).each_with_index do |standing, index| %>
            <tr class="<%= standing.is_current_user?(current_user) %>">
              <td><%= index + 1 %></td>
              <td><%= standing.identifier %></td>
              <td><%= standing.pick_count %></td>
            </tr>
          <% end %>
          <% unless @season.standings(3).include?(current_user) %>
            <tr class="bg-dark text-white">
              <% user_standing = @season.position_for_current_user(current_user) %>
              <td><%= user_standing[:place] %></td>
              <td><%= user_standing[:object]&.identifier %></td>
              <td><%= user_standing[:object]&.pick_count %></td>
          <% end %>
          <tr>
            <td colspan="3">
              <%= link_to "View full standings", standings_season_path(@season) %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <h5>Today + Next 7 Days</h5>
      <div class="table-responsive">
        <table class="table table-sm table-striped">
          <tr>
            <th>Date</th>
            <th>Pick</th>
            <th class="text-center">Most Picked</th>
          </tr>
          <% @current_week.each do |date| %>
            <% formatted_date = formatted_date(date) %>
            <% pick = @all_picks.by_date(date, current_user) %>
            <% week = GameWeek.by_date(@season, date) %>
            <tr>
              <td>
                <a name="<%= formatted_date.parameterize.underscore %>"><%= formatted_date %></a>
              </td>

              <td>
                <% if pick %>
                  <div class="<%= pick.winner_css %> existing_pick nowrap">
                    <span><%= pick.team.decorate.full_name %></span>
                    <% unless (week.locked? || !@season.active?)%>
                      <%= button_to pick, method: :delete, class: "btn btn-outline-danger", form_class: "delete_pick" do %>
                        <%= fa_icon "times fw" %>
                      <% end %>
                    <% end %>
                  </div>
                <% else %>
                  <% if @season.active? %>
                    <% if week.locked? %>
                      Cutoff has passed. No pick.
                    <% else %>
                      <%= form_for Pick.new, html: { class: 'new-pick'  } do |f| %>
                        <%= f.hidden_field :game_week_id, value: week.id %>
                        <%= f.hidden_field :date, value: date %>
                        <div class="form-group select-new-pick">
                          <%= f.collection_select(:team_id, Team.all.decorate, :id, :full_name, {include_blank: true}, {class: "form-control"}) %>
                          <%= button_tag class: "btn btn-outline-primary save-pick" do %>
                            <%= fa_icon "check fw" %>
                          <% end %>
                        </div>
                      <% end %>
                    <% end %>
                  <% end %>

                <% end %>
              </td>

              <td class="text-center">
                <% if week.locked? %>
                  <%= Team.most_by_season_and_date(@season, date) %>
                <% end %>
              </td>
            </tr>
          <% end %>
          <tr colspan="3">
            <td><%= link_to "View my picks", picks_path(season_id: @season) %></td>
            <td><%= link_to "View everyone's picks", picks_path(season_id: @season, view_all: "true") %></td>
          </tr>
        </table>
      </div>
    </div>

  </div>

</div>