config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  get "/dashboard", to: "dashboard#show", as: "dashboard"

  resources :leagues
  resources :seasons, except: [:index] do
    member do
      get "standings", to: "standings#show"
    end
  end

  resources :picks, only: [:index, :create, :destroy]

  namespace :admin do
    get "/winners", to: "winners#index"
    post "/winners", to: "winners#create"
  end

  get "/unsubscribe", to: "unsubscribe#reminders"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def show
  end
end

app/views/dashboard/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="button-actions-row">
        <%= link_to "New League", new_league_path, class: "btn btn-outline-primary btn-sm" %>
      </div>
      <div class="row justify-content-between">
        <div class="col-md-6">
          <h4>Active Seasons</h4>
          <table class="table table-sm">
            <tr>
              <th>Season Name</th>
              <th>Player Count</th>
              <th>Current Position</th>
              <th>Days left</th>
            </tr>
            <% current_user.active_seasons.each do |season| %>
              <tr>
                <td><%= link_to season.name, season_path(season) %></td>
                <td><%= season.player_count %></td>
                <td><%= season.position_for_current_user(current_user)[:place] %></td>
                <td><%= season.days_left %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div clas="col-md-6">
          <h4>Leagues</h4>
          <table class="table table-sm">
            <tr>
              <th>League Name</th>
              <th>Number of Seasons</th>
              <th>Role</th>
            </tr>
            <% current_user.user_leagues.each do |league| %>
              <tr>
                <td>
                  <%= link_to league.name, league %>
                </td>
                <td>
                  <%= league.seasons.count %>
                </td>
                <td>
                  <%= league.role_for_user(current_user) %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>