config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  get "/dashboard", to: "dashboard#show", as: "dashboard"

  resources :leagues
  resources :seasons, except: [:index] do
    member do
      get "standings", to: "standings#show"
    end
  end

  resources :picks, only: [:index, :create, :destroy]

  namespace :admin do
    get "/winners", to: "winners#index"
    post "/winners", to: "winners#create"
  end

  get "/unsubscribe", to: "unsubscribe#reminders"
end

app/models/league.rb
class League < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "user_id"
  has_many :memberships, dependent: :destroy
  has_many :seasons

  after_create_commit :create_admin_membership

  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false

  def role_for_user(user)
    memberships.find_by(user: user)&.role
  end

  private

  def create_admin_membership
    memberships.create(user_id: user_id, role: 1)
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @league = League.find(params[:id])
    authorize @league
  end

  def new
    @league = current_user.leagues.new
  end

  def create
    @league = current_user.leagues.new(league_params)
    if @league.save
      redirect_to @league
    else
      render :new
    end
  end

  def edit
    @league = League.find(params[:id])
    authorize @league
  end

  def update
    @league = League.find(params[:id])
    authorize @league
    if @league.update(league_params)
      redirect_to @league
    else
      render :edit
    end
  end

  def destroy
    league = League.find(params[:id])
    authorize league
    league.destroy!
    redirect_to dashboard_path
  end

  private

  def league_params
    params.require(:league).permit(:name)
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/edit.html.erb
<%= form_for @league do |f| %>
  <%= f.label :name, "League Name" %>
  <%= f.text_field :name %>
  <%= f.submit "Update League" %>
<% end %>

app/views/leagues/new.html.erb
<div class="container">
  <div class="row one-half-column">
    <div class="one-half column">
      <%= form_for @league do |f| %>
        <div class="field">
          <%= f.label :name, "League Name" %>
          <%= f.text_field :name, class: "u-full-width" %>
        </div>
        <div class="actions">
          <%= f.submit "Create League", class: "u-full-width" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/leagues/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="button-actions-row">
        <% if policy(@league).destroy? %>
          <%= button_to "Delete League", @league, method: :delete, class: "btn btn-danger", form_class: "delete-league" %>
        <% end %>
        <%= link_to "New Season", new_season_path(league_id: @league.id), class: "btn btn-outline-primary" %>
      </div>
      <h4>League Name: <%= @league.name %></h4>
      <h4>Seasons</h4>
      <table class="table table-sm table-responsive-sm">
        <tr>
          <th>Season Name</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Days in Season</th>
        </tr>
      <% @league.seasons.decorate.each do |season| %>
        <tr>
          <td><%= link_to season.name, season %></td>
          <td><%= season.formatted_start_date %></td>
          <td><%= season.formatted_end_date %></td>
          <td><%= season_days(season) %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>