config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users

  get "/dashboard", to: "dashboard#show", as: "dashboard"

  resources :leagues
  resources :seasons, except: [:index] do
    member do
      get "standings", to: "standings#show"
    end
  end

  resources :picks, only: [:index, :create, :destroy]

  namespace :admin do
    get "/winners", to: "winners#index"
    post "/winners", to: "winners#create"
  end

  get "/unsubscribe", to: "unsubscribe#reminders"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">MLB PICK-A-WINNER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <% if current_user %>
        <% if current_user.superadmin? %>
          <li class="nav-item">
            <%= link_to "admin", admin_winners_path, class: "nav-link custom text-danger" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "dashboard", dashboard_path, class: "nav-link custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "log out", destroy_user_session_path, method: :delete, class: "nav-link custom" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "log in", new_user_session_path, class: "nav-link custom" %>
        </li>
        <li class="nav-item">
          <%= link_to "sign up", new_user_registration_path, class: "nav-link custom" %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>